# Introduction to Tensors

In [ ]:
# Import all relevant libraries
# pytorch, pandas, numpy, matplotlib.pyplot

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu128


## Creating tensors

PyTorch tensors can be created using "torch.Tensor()"

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [6,7]])
MATRIX

tensor([[7, 8],
        [6, 7]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([6, 7])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[3,4,9],
                        [5,8,9],
                        [7,4,9]]])
TENSOR

tensor([[[3, 4, 9],
         [5, 8, 9],
         [7, 4, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[3, 4, 9],
        [5, 8, 9],
        [7, 4, 9]])

In [ ]:
TENSOR[0][0]

tensor([3, 4, 9])

In [ ]:
TENSOR[0][1]

tensor([5, 8, 9])

In [ ]:
TENSOR[0][2]

tensor([7, 4, 9])

# Creating random tensors

In [ ]:
# Create random tensor of size (3, 5) => 15 elements

3 * 5

15

In [ ]:
random_tensor = torch.rand(3, 5)
random_tensor

tensor([[0.8755, 0.6661, 0.4235, 0.1697, 0.3616],
        [0.9419, 0.0335, 0.4003, 0.5918, 0.6997],
        [0.2785, 0.5237, 0.1721, 0.8657, 0.6194]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 5])

Creating a random tensor with similar shape to an image

In [ ]:
# rand(height, with, number of color channels)

random_image_size_tensor = torch.rand(224, 224, 3)
random_image_size_tensor

tensor([[[0.4875, 0.5604, 0.7171],
         [0.5653, 0.2500, 0.1447],
         [0.6442, 0.4032, 0.3935],
         ...,
         [0.3916, 0.6259, 0.3527],
         [0.2860, 0.2278, 0.0487],
         [0.8666, 0.1789, 0.1317]],

        [[0.7136, 0.1107, 0.8178],
         [0.9673, 0.2138, 0.6335],
         [0.7013, 0.6074, 0.9184],
         ...,
         [0.9926, 0.6059, 0.3525],
         [0.2508, 0.4929, 0.4847],
         [0.9459, 0.5978, 0.8275]],

        [[0.7104, 0.7835, 0.1579],
         [0.0242, 0.1306, 0.5514],
         [0.1160, 0.6320, 0.1576],
         ...,
         [0.8820, 0.6468, 0.9635],
         [0.7566, 0.0636, 0.3787],
         [0.9050, 0.2975, 0.1155]],

        ...,

        [[0.5139, 0.3314, 0.1802],
         [0.6201, 0.1772, 0.7342],
         [0.8224, 0.3357, 0.1351],
         ...,
         [0.7607, 0.9040, 0.0947],
         [0.0235, 0.3365, 0.6563],
         [0.2777, 0.9269, 0.7921]],

        [[0.7342, 0.1760, 0.4853],
         [0.1639, 0.3709, 0.6684],
         [0.

In [ ]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
random_image_size_tensor.ndim

3

Creating tensors with zeros and ones

In [ ]:
# Create a tensorof all zeros
zeros = torch.zeros(size=(3,5))
print(zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# Check tensor datatype
ones.dtype

torch.float32

In [ ]:
# Check tensor datatype
random_image_size_tensor.dtype

torch.float32

Creating a range of tensors and tensors-like

In [ ]:
# Using torch.range()
# If you get a deprecated message, use torch.arange()
# Create tensor from 1 to 10
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Create tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

**Note:** Below are the 3 main issues you'll commonly face in PyTorch and deep learning:
1. Tensors not in right **datatype**
2. Tensors not in right **shape**
1. Tensors not on right **device**

Read more on precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# Change tensor datatype from Float 32 to Float 16
float_16_tensor = torch.tensor([3.0, 7.0, 9.0],
                               dtype=torch.float16, # Tensor datatype e.g. float32 or float16
                               device=None, # What device to run tensor on. Can be changed to "cpu" or "cuda"
                               requires_grad=False) # Whether or not to track gradients with this tensor's operations
float_16_tensor

tensor([3., 7., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
# Convert float32 tensor to float16 tensor
another_float_16_tensor = float_32_tensor.type(torch.float16)
another_float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# Multiply tensors of 2 different datatypes (float16 & float32)
# Returns default float32 tensor
multiplication_result = float_32_tensor * float_16_tensor
multiplication_result

tensor([ 9., 42., 81.])

In [ ]:
multiplication_result.dtype

torch.float32

Getting information from tensors

1. To get tensor datatype, we use `tensor.dtype`
2. To get tensor shape, there's 2 ways. Using an attribute, we use `tensor.shape`. Using a function, we use `tensor.size()`
3. To get tensor device, we use `tensor.device`

In [ ]:
# Create random tensor
some_random_tensor = torch.rand(3,4)
some_random_tensor

tensor([[0.4172, 0.8934, 0.3084, 0.3098],
        [0.9047, 0.5068, 0.9177, 0.6654],
        [0.0403, 0.4449, 0.1140, 0.0436]])

In [ ]:
# Find out some details about tensor
print(f"Datatype of tensor: {some_random_tensor.dtype}")
print(f"Shape of tensor using attribute: {some_random_tensor.shape}")
print(f"Shape of tensor using function: {some_random_tensor.size()}")
print(f"Device of tensor: {some_random_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor using attribute: torch.Size([3, 4])
Shape of tensor using function: torch.Size([3, 4])
Device of tensor: cpu


Manipulating tensors / Tensor Operations

# Tensor operations include the following:

**1.** Addition

**2.** Subtraction

**3.** Multiplication (element-wise)

**4.** Division

**5.** Matrix multiplication (dot product)

In [ ]:
# Addition
# Create a tensor and add 100 to it
tensor = torch.tensor([1,2,4])
tensor + 100

tensor([101, 102, 104])

In [ ]:
# For addition, we can also use a function `torch.add`
tensor_add = torch.tensor([4,5,6])
torch.add(tensor_add, 10)

tensor([14, 15, 16])

In [ ]:
# Subtraction
# Create a tensor and subtract 100 from it
tensor = torch.tensor([1,2,4])
tensor - 100

tensor([-99, -98, -96])

In [ ]:
# Multiplication
# Create a tensor and multiply it by 100
tensor = torch.tensor([1,2,4])
tensor * 100

tensor([100, 200, 400])

In [ ]:
# For multiplication, we can also use a function `torch.mul`
tensor_mul = torch.tensor([4,5,6])
torch.mul(tensor_mul, 10)

tensor([40, 50, 60])

In [ ]:
# Division
# Create a tensor and multiply it by 100
tensor = torch.tensor([1,2,4])
tensor * 100

tensor([100, 200, 400])

Matrix multiplication

There's 2 main ways of multiplying matrices
1. Element-wise multiplication
2. Matrix multiplication (dot product)

Read more here: https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [49]:
# Element wise multiplication
print (tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 4]) * tensor([1, 2, 4])
Equals: tensor([ 1,  4, 16])


In [50]:
# Matrix multiplication (Dot Product)
torch.matmul(tensor, tensor)

tensor(21)

In [51]:
# Matrix multiplication by hand
{1*1 + 2*2 + 4*4}

{21}

Testing the speed of using matmul vs. multiplication by hand

In [54]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(21)
CPU times: user 1.64 ms, sys: 68 µs, total: 1.71 ms
Wall time: 1.44 ms


In [55]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 335 µs, sys: 36 µs, total: 371 µs
Wall time: 197 µs


tensor(21)

There are 2 main rules we must satisfy when performing matrix multiplication:

1. The **inner dimensions** must match


*   (3,**2**) @ (**3**,2) won't work
*   (2,**3**) @ (**3**,2) will work
*   (3,**2**) @ (**2**,3) will work

The above is what's called **"shape errors"**

2. The resulting matrix has the shape of the **outer dimensions**
*   (3,**2**) @ (**2**,3) results into (3,3)

In [57]:
### Example error for inner dimensions mismatch
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [61]:
### Example of how to fix the above error simply by making sure inner dimensions match
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.1681, 0.3887, 0.8516],
        [0.2729, 0.2316, 0.1818],
        [0.2996, 0.4633, 0.8276]])

How to deal with **Shape Errors**

In [77]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])

tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [64]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

# To fix our tensor issues, we can manipulate the shape of one of the tensors using a **transpose**

**A transpose** swicthes the axes or dimensions of a given tensor

In [71]:
# Original tensor
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [73]:
# Transposed tensor
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [74]:
## The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")

output = torch.mm(tensor_A, tensor_B.T)

print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


# Tensor Aggregation

Finding the min, max, mean, sum etc of tensors
