# Introduction to Tensors

In [ ]:
# Import all relevant libraries
# pytorch, pandas, numpy, matplotlib.pyplot

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


## Creating tensors

PyTorch tensors can be created using "torch.Tensor()"

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [6,7]])
MATRIX

tensor([[7, 8],
        [6, 7]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([6, 7])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[3,4,9],
                        [5,8,9],
                        [7,4,9]]])
TENSOR

tensor([[[3, 4, 9],
         [5, 8, 9],
         [7, 4, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[3, 4, 9],
        [5, 8, 9],
        [7, 4, 9]])

In [ ]:
TENSOR[0][0]

tensor([3, 4, 9])

In [ ]:
TENSOR[0][1]

tensor([5, 8, 9])

In [ ]:
TENSOR[0][2]

tensor([7, 4, 9])

# Creating random tensors

In [ ]:
# Create random tensor of size (3, 5) => 15 elements

3 * 5

15

In [ ]:
random_tensor = torch.rand(3, 5)
random_tensor

tensor([[0.6643, 0.9446, 0.7800, 0.0762, 0.4213],
        [0.3819, 0.8732, 0.9792, 0.6572, 0.2057],
        [0.8214, 0.1713, 0.1065, 0.0468, 0.5714]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 5])

Creating a random tensor with similar shape to an image

In [ ]:
# rand(height, with, number of color channels)

random_image_size_tensor = torch.rand(224, 224, 3)
random_image_size_tensor

tensor([[[9.1366e-01, 9.1667e-01, 9.0905e-01],
         [5.5916e-01, 8.4691e-01, 7.6372e-01],
         [9.1856e-01, 7.9515e-01, 4.8148e-02],
         ...,
         [8.5236e-01, 2.6060e-02, 3.3337e-01],
         [1.2340e-01, 7.1143e-01, 9.3500e-01],
         [8.0813e-01, 7.7159e-01, 4.2740e-01]],

        [[1.8441e-02, 6.8245e-01, 3.2418e-01],
         [6.5582e-01, 8.2068e-01, 4.8387e-01],
         [6.0959e-01, 8.1859e-01, 3.1765e-01],
         ...,
         [5.6165e-01, 9.4045e-02, 7.5711e-01],
         [7.5971e-01, 4.6146e-01, 5.5155e-01],
         [8.2094e-02, 6.0379e-01, 4.1648e-01]],

        [[5.5694e-01, 1.2845e-01, 7.3750e-01],
         [8.7313e-01, 6.3811e-02, 8.1029e-01],
         [3.0947e-01, 8.1505e-01, 9.9907e-01],
         ...,
         [8.6117e-01, 3.3575e-04, 7.0649e-01],
         [8.3927e-01, 8.0925e-01, 8.3616e-03],
         [1.5784e-01, 8.4398e-01, 9.1262e-01]],

        ...,

        [[8.6885e-01, 9.2931e-01, 2.5762e-01],
         [9.5330e-01, 3.1286e-01, 4.9194e-01]

In [ ]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
random_image_size_tensor.ndim

3

Creating tensors with zeros and ones

In [60]:
# Create a tensorof all zeros
zeros = torch.zeros(size=(3,5))
print(zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [61]:
zeros * random_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [62]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [66]:
# Check tensor datatype
ones.dtype

torch.float32

In [67]:
# Check tensor datatype
random_image_size_tensor.dtype

torch.float32

Creating a range of tensors and tensors-like

In [69]:
# Using torch.range()
# If you get a deprecated message, use torch.arange()
# Create tensor from 1 to 10
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
# Create tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

In [72]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [73]:
float_32_tensor.dtype

torch.float32